version: '3.8'

services:
  node-app:
    build: .
    command: node dist/index.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/norfabagas-betest
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:8.0.0-rc5-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: